// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrFRvlXjR00ECVGicmbjPbKQq_EYVszMw',
    appId: '1:115928479310:web:b381e658b67cb4bf3df51f',
    messagingSenderId: '115928479310',
    projectId: 'ai-expenso',
    authDomain: 'ai-expenso.firebaseapp.com',
    storageBucket: 'ai-expenso.firebasestorage.app',
    measurementId: 'G-V7N04065QR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqo_k31M44eG8jpe4nUQ9WJzf1N4RWrEA',
    appId: '1:115928479310:android:ba4eaca8283d2d903df51f',
    messagingSenderId: '115928479310',
    projectId: 'ai-expenso',
    storageBucket: 'ai-expenso.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7K_PrVM5cbFsLk9AU1UbGBLk9-UrdGjg',
    appId: '1:115928479310:ios:8947b8a6c54a483c3df51f',
    messagingSenderId: '115928479310',
    projectId: 'ai-expenso',
    storageBucket: 'ai-expenso.firebasestorage.app',
    androidClientId: '115928479310-2mi0fbrr9mqs4v3snvih2jtk5ch5tf7b.apps.googleusercontent.com',
    iosClientId: '115928479310-9p0le6hm0rpgnvrkid2kl4ds2501m6aj.apps.googleusercontent.com',
    iosBundleId: 'com.expenso.ai.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7K_PrVM5cbFsLk9AU1UbGBLk9-UrdGjg',
    appId: '1:115928479310:ios:8947b8a6c54a483c3df51f',
    messagingSenderId: '115928479310',
    projectId: 'ai-expenso',
    storageBucket: 'ai-expenso.firebasestorage.app',
    androidClientId: '115928479310-2mi0fbrr9mqs4v3snvih2jtk5ch5tf7b.apps.googleusercontent.com',
    iosClientId: '115928479310-9p0le6hm0rpgnvrkid2kl4ds2501m6aj.apps.googleusercontent.com',
    iosBundleId: 'com.expenso.ai.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrFRvlXjR00ECVGicmbjPbKQq_EYVszMw',
    appId: '1:115928479310:web:11c166f34f47d0a13df51f',
    messagingSenderId: '115928479310',
    projectId: 'ai-expenso',
    authDomain: 'ai-expenso.firebaseapp.com',
    storageBucket: 'ai-expenso.firebasestorage.app',
    measurementId: 'G-930C6GQ59Q',
  );
}
